config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: [:index, :show, :new,  :create] do
    # member do
    #   # post :bookmarks

    # end
    post "bookmarks", to: "bookmarks#create"
    get "bookmarks/new", to: "bookmarks#new"
    delete "bookmarks/:id", to: "bookmarks#destroy"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 5 }
  validates_uniqueness_of :movie, scope: [:list]
  validates_uniqueness_of :list, scope: [:movie]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  # , dependent: :restrict

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    # @bookmark = Bookmark.new(review_params)
    # @bookmark.list = @list
    @movie = Movie.find(params[:bookmark][:movie])
    @comment = params[:bookmark][:comment]
    @bookmark = Bookmark.new(list: @list, movie: @movie, comment: @comment)
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path, status: :see_other
  end

  private

  def review_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(review_params)
    @list.save
    redirect_to lists_path
  end


  private

  def review_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="navbar-lewagon">
  <%= image_tag "reel.png", alt: "Le Wagon"%>
  <div class="links">
    <%= link_to "List", lists_path%>
  </div>
</div>

<div class="container">
  <%= simple_form_for [@list,@bookmark] do |f| %>
    <%= f.input :movie, collection: Movie.all %> <%# <%= f.association  :movie %>
    <%= f.input :comment %>
    <%= f.submit "Add a movie", class:"btn btn-primary"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_navbar.html.erb
<div class="navbar-lewagon">
  <%= image_tag "reel.png", alt: "Le Wagon"%>
  <div class="links">
    <%= link_to "New", new_list_path %>
  </div>
</div>

app/views/lists/index.html.erb
<%= render "navbar", list: @list %>

<div class="bannerImg">
  <div class="header-title">
    <h1>Let's explore Movies</h1>
  </div>
</div>

<div class="cards-container">
  <% @lists.each do |list|%>
    <div class="card" style="width: 18rem;">
      <p class="card-text"><%= link_to list.name, list_path(list) %></p>
    </div>
  <% end  %>
</div>

app/views/lists/new.html.erb
<div class="navbar-lewagon">
  <%= image_tag "reel.png", alt: "Le Wagon"%>
  <div class="links">
    <%= link_to "List", lists_path%>
  </div>
</div>
<div class="container">
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit class:"btn btn-primary"%>
<% end %>
</div>

app/views/lists/show.html.erb
<div class="navbar-lewagon">
  <%= image_tag "reel.png", alt: "Movies"%>
  <div class="links">
    <%= link_to "List", lists_path%>
    <%= link_to "Add a movie", list_bookmarks_new_path(@list)%>
  </div>
</div>

<div class="container">
  <h1 class="display-3"><%= @list.name %></h1>

<div class="cards-container">
  <% @list.movies.each do |movie|%>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src=<%= movie.poster_url %> alt="Card image cap">
      <div class="card-body">
          <p class="card-text"><%= movie.overview %></p>
          <p><strong>Reviews</strong></p>
            <% movie.bookmarks.each do |bm|%>
              <p><%= bm.comment %>  <%= link_to "Delete", "/lists/#{@list.id}/bookmarks/#{bm.id}" ,data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-primary"%><p/>
            <% end  %>
      </div>
    </div>
  <% end  %>
</div>

</div>